language: node_js
node_js:
  - "stable"

script:
  - yarn
  - yarn test
  - yarn build

deploy:
  provider: surge
  skip_cleanup: true
  domain: 'react-testing-demo-ahmedfaraz.surge.sh'
  project: './build'

on:
  branch: main